version: "3.8"

services:
  web:
    build:
      context: .  
    container_name: aromanil-container
    command: gunicorn aromanil.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  
    ports:
      - "8035:8000"  
    networks:
      - mynetwork  
    restart: unless-stopped 

networks:
  mynetwork:
    driver: bridge  
